version: '3'
services:

  traefik:
    image: traefik:v2.5
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #lee los servicios que se van creando
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:/acme.json
    
    networks:  
      - microservicio_network

  postgresql:
    container_name: postgresql
    image: postgres:15.6-bullseye
    networks:
      - microservicio_network
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/data
    volumes:
      - ./data:/var/lib/data

  redis:
    container_name: redis
    image: redis:7.2.4-bookworm
    networks:
      - microservicio_network
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      
  microserviceClient:
    image: microservice_client:1.0
    networks:
      - microservicio_network
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microserviceClient.rule=Host(`microserviceClient.localhost`)"
      - "traefik.http.routers.microserviceClient.entrypoints=web"

networks:
  microservicio_network:
    driver: bridge