version: '3'
services:

  traefik:
    image: traefik:v2.5
    command:
      --api.insecure=true
      --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:  
      - microservicio_network

  postgresql:
    container_name: postgresql
    image: postgres:15.6-bullseye
    networks:
      - microservicio_network
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/data
    volumes:
      - ./data:/var/lib/data
    depends_on:
      - traefik

  redis:
    container_name: redis
    image: redis:7.2.4-bookworm
    networks:
      - microservicio_network
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    depends_on:
      - postgresql
      
  microserviceClient:
    image: microservice_client:1.0
    networks:
      - microservicio_network
    ports:
      - "8081:8081"
    depends_on:
      - redis
    labels:
      - "traefik.http.routers.microserviceClient.rule=Host(\"microserviceClient.localhost\")"

networks:
  microservicio_network:
    driver: bridge