services:

    postgresql:
      container_name: postgres
      image: postgres:15.6-bullseye
      networks:
        - microservice_network
      # ports: 
      #   - "5433:5432"
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - PGDATA=/var/lib/data
      volumes:
        - ./data/postgres:/var/lib/data
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.postgresql.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.postgresql.entryPoints=postgresql"
        - "traefik.tcp.services.postgresql.loadbalancer.server.port=5432"

    redis:
      container_name: redis
      image: redis:7.2.4-bookworm
      networks:
        - microservice_network
      # ports:
      #   - "6379:6379"
      volumes:
        - ./data/redis:/data
      labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis.entryPoints=redis"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"
      depends_on:
        - postgresql

networks:
  microservice_network:
    external: true