http:
  routers:
    traefik:
      rule: "Host(`traefik.microservicio.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "microservicio.localhost"
            sans:
              - "*.microservicio.localhost"
          - main: "microservicio.local"
            sans:
              - "*.microservicio.local"

tls:
  certificates:
    - certFile: "/etc/certs/microservicio-cert.pem"
      keyFile: "/etc/certs/microservicio-key.pem"