"""empty message

Revision ID: bde691eee40a
Revises: 
Create Date: 2024-06-07 20:58:31.183359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde691eee40a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=105), nullable=True),
    sa.Column('dni', sa.String(length=9), nullable=True),
    sa.Column('code', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=105), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
